# Generated by Django 5.2.1 on 2025-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lcid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='College ID'),
        ),
    ]
