# Generated by Django 5.2.1 on 2025-06-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0004_order_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepare_duration',
            field=models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes')], default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
