# Generated by Django 5.2.1 on 2025-09-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0005_field_remove_portfolio_user_remove_project_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('youtube_url', models.URLField()),
                ('youtube_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('fields', models.ManyToManyField(blank=True, related_name='course_videos', to='canteenApp.field')),
                ('interests', models.ManyToManyField(blank=True, related_name='course_videos', to='canteenApp.interest2')),
                ('skills', models.ManyToManyField(blank=True, related_name='course_videos', to='canteenApp.skill2')),
                ('keywords', models.ManyToManyField(blank=True, related_name='videos', to='canteenApp.videokeyword')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='canteenApp__categor_916cf0_idx'), models.Index(fields=['youtube_id'], name='canteenApp__youtube_a2fdd5_idx')],
            },
        ),
    ]
