# Generated by Django 5.2.1 on 2025-09-03 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0006_videokeyword_coursevideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My AI Classroom', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='canteenApp.coursevideo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='canteenApp.coursevideo')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContextSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.PositiveIntegerField()),
                ('end_seconds', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='canteenApp.videocontext')),
            ],
            options={
                'ordering': ['start_seconds'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_watched_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='canteenApp.classroom')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_items', to='canteenApp.coursevideo')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('classroom', 'video')},
            },
        ),
    ]
