# Generated by Django 5.2.1 on 2025-06-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0007_product_is_active_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
