# Generated by Django 5.2.1 on 2025-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0007_classroom_videocontext_videocontextsegment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomitem',
            name='note',
            field=models.TextField(default='Video Note!'),
        ),
    ]
