# Generated by Django 5.2.1 on 2025-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0008_alter_classroomitem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='notes',
            field=models.TextField(blank=True, default='Video Note!'),
        ),
    ]
