# Generated by Django 5.2.1 on 2025-06-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0010_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
