# Generated by Django 5.2.1 on 2025-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0019_order_refunded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
