# Generated by Django 5.2.1 on 2025-07-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0020_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prepare_duration',
            field=models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '20 minutes')], default=10),
        ),
    ]
