# Generated by Django 5.2.1 on 2025-07-21 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0021_alter_order_prepare_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='table',
            name='area',
            field=models.CharField(choices=[('Main Hall', 'Main Hall'), ('Window Side', 'Window Side'), ('Counter Side', 'Counter Side'), ('Private Section', 'Private Section')], default='Main Hall', max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='estimated_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='occupied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guests', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='canteenApp.table')),
            ],
        ),
    ]
