# Generated by Django 5.2.1 on 2025-07-21 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0022_remove_table_is_occupied_table_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
