# Generated by Django 5.2.1 on 2025-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0024_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
