# Generated by Django 5.2.1 on 2025-07-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteenApp', '0026_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
